import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layout/Footer';
import clsx from 'clsx';

const notoSansJP = Noto_Sans_JP({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={clsx(
          notoSansJP.className,
          'flex min-h-screen flex-col text-dark-600'
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
